# Generated by Django 4.2 on 2024-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='views',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_session',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сессия по оплате'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
