# Generated by Django 4.2 on 2024-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_session',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сессия по оплате'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
