# Generated by Django 4.2 on 2024-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menenger', '0003_alter_content_author_alter_content_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='count_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
