# Generated by Django 4.2 on 2024-06-15 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menenger', '0006_content_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк/Дизлайк')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menenger.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
